name: Deployment on aws lambda

on:
  push:
    branchs: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Run Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --all-features --target=${{ matrix.target }}

      - name: Rename binary to bootstrap
        run: "mv ./rust_lambda ./bootstrap"
        working-directory: ./target/x86_64-unknown-linux-musl/release

      - name: Zip Code for Deployment
        run: "sudo zip -j lambda.zip bootstrap"
        working-directory: ./target/x86_64-unknown-linux-musl/release

       - name: Run Build
         run: cargo lambda deploy --iam-role FULL_ROLE_ARN --enable-function-url http-lambda
        




        


