name: RustDeployment AWS Lambda

on:
  push:
    branchs: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        toolchain:
          - "1.62.0" # Current MSRV
        target:
          - x86_64-unknown-linux-musl
        include:
          - rust: nightly
            allow_failure: true
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --all --verbose
        env:
          TARGET: ${{ matrix.target }}
        continue-on-error: ${{ matrix.allow_failure }}
      - name: Run tests
        run: cargo test --all --verbose
        env:
          TARGET: ${{ matrix.target }}
        continue-on-error: ${{ matrix.allow_failure }}
      - name: Deploy
        run: echo "Deploying..."
        env:
          TARGET: ${{ matrix.target }}
        continue-on-error: ${{ matrix.allow_failure }}

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2

      - name: Run fmt check
        run: cargo fmt --all -- --check
      - name: Run clippy check
        run: cargo clippy --all-features -- -D warnings

